### ISSUE TITLE
[Bug]: Wouldn't it be better to remove the backend?

### ISSUE THREAD

**Issue by joojae02** [fing9/ProblemRandomDefence#1]
## Hellow Fin. 
I think these codes can be replaced with serverless.. or something.  
Because I think the backend using Spring is over-engineered in this project.  
I would appreciate it if you would consider my opinion. 🙇 

저는 백엔드의 일부 기능을 제거하는 것에 대해 의견을 제시하고자 합니다. 이는 프로젝트의 구조와 성능에 어떤 영향을 미칠지 고민해 볼 주제입니다.  
이 이슈를 통해 논의하고 다른 의견을 듣고자 합니다. 의견을 자유롭게 나눠봅시다. 감사합니다!  

> 출처 : 내 머리.

**Comment by hdaisywd** [comment]
흠.... 확실히 타당한데요?

**Comment by fing9** [comment]
제안인데 왜 버그죠..??

일단 오버 엔지니어링은 경계하고 있습니다.

그럼 닫도록 하겠습니다. 감사합니다.

**Comment by joojae02** [comment]
> 제안인데 왜 버그죠..??
> 
> 일단 오버 엔지니어링은 경계하고 있습니다.
> 
> 그럼 닫도록 하겠습니다. 감사합니다.

쩝

**Comment by hdaisywd** [comment]
> 제안인데 왜 버그죠..??
> 
> 일단 오버 엔지니어링은 경계하고 있습니다.
> 
> 그럼 닫도록 하겠습니다. 감사합니다.

쩝
