### ISSUE TITLE
[요청] 랜덤문제 추천하는 api 권한 전체 허용해주세요

### ISSUE THREAD

**Issue by klloo** [fing9/ProblemRandomDefence#11]
메인 화면에서 로그인 안해도 랜덤문제 추천은 받을 수 있도록 해주세요 ! !

**Comment by fing9** [comment]
빠른 시일안에 반영하겠습니다

**Comment by fing9** [comment]
빠른 시일안에 반영하겠습니다 - 2

**Comment by fing9** [comment]
@klloo 권한 허용했습니다. develop에서 배포하면 또 알림 드리겠습니다.

**Comment by fing9** [comment]
@klloo 알려드리는게 늦었는데 마지막 배포 때 적용 완료했습니다.
