### ISSUE TITLE
[BUG] 이미 작성된 게시글을 수정할 때, 이미지를 첨부하면 일정 시간 뒤 S3 저장소에서 이미지가 삭제되는 문제

### ISSUE THREAD

**Issue by fing9** [fing9/ProblemRandomDefence#6]
## 상세
이미 작성된 게시글을 수정할 때, 이미지를 첨부하면 일정 시간 뒤 S3 저장소에서 이미지가 삭제되는 문제

## 원인
게시글을 작성하다가 중간에 글을 완성하지 않고 나가는 경우, S3 서버에 업로드했던 이미지들을 일정 시간이 지나면 삭제하는 메서드가 주기적으로 동작한다.

이 메서드는 업로드된 이미지에 대한 삭제 여부를 image가 가지고있는 Published 값이 False라면 생성 시간을 보고 일정 시간이 지났는지에 따라 삭제 여부를 판단한다.

이는 Published 값을 게시글이 publish 될 때, True로 변경해주어 이미지 저장 확정을 결정하는 방식이다.

이 Published 값이 게시글이 수정될 때, 수정 시에 첨부된 이미지에 대해 True로 변경되지 않기 때문에 발생하는 문제이다.

**Comment by fing9** [comment]
백엔드 코드 리뷰했는데 크게 문제 없어보임. 프론트 버그일 가능성이 큼

**Comment by klloo** [comment]
프론트 버그 맞음 . 수정 완 .
